### ISSUE TITLE
Zone schedule is not set until the sensor is detected after startup

### ISSUE THREAD

**Issue by climategadgets** [home-climate-control/dz#10]
- Expected result: the schedule is set on the zone
- Actual result: the schedule is not set and an exception trace is repeatedly logged until the sensor appears.

Exception trace:

```
14:27:28,443 ERROR Scheduler pool-20-thread-1 [run execute] Dining Room: failed to set schedule, will retry on next run
java.lang.NullPointerException
        at net.sf.dz3.controller.pid.AbstractPidController.compute(AbstractPidController.java:236)
        at net.sf.dz3.controller.AbstractProcessController.wrapCompute(AbstractProcessController.java:163)
        at net.sf.dz3.controller.AbstractProcessController.setSetpoint(AbstractProcessController.java:73)
        at net.sf.dz3.device.model.impl.ThermostatModel.setSetpoint(ThermostatModel.java:360)
        at net.sf.dz3.device.model.impl.ThermostatModel.set(ThermostatModel.java:513)
        at net.sf.dz3.scheduler.Scheduler.execute(Scheduler.java:353)
        at net.sf.dz3.scheduler.Scheduler.execute(Scheduler.java:315)
        at net.sf.dz3.scheduler.Scheduler.run(Scheduler.java:230)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
```

**Comment by climategadgets** [comment]
Reactive overhaul took care of this; the schedule is now set in a graceful way.
