### ISSUE TITLE
HVAC uptime counter breaks when the system runs out of disk space

### ISSUE THREAD

**Issue by climategadgets** [home-climate-control/dz#146]
* Event: System runs out of disk space
* Expected result: the counter gracefully stops updates
* Actual result: the counter sets the file size to zero, which renders the system inoperable on the next start

**Comment by climategadgets** [comment]
Exception trace on system start:
```
Caused by: java.lang.IllegalArgumentException: No 'threshold=NN' found in /home/dz/dz3-shell/counter-hvac-workshop
        at net.sf.dz3.util.counter.FileUsageCounter.load(FileUsageCounter.java:105) ~[dz3-common-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.util.counter.AbstractUsageCounter.<init>(AbstractUsageCounter.java:111) ~[dz3-common-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.util.counter.TransientUsageCounter.<init>(TransientUsageCounter.java:56) ~[dz3-common-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.util.counter.FileUsageCounter.<init>(FileUsageCounter.java:36) ~[dz3-common-3.6.8-SNAPSHOT.jar:?]
```

**Comment by climategadgets** [comment]
Superseded by #232. Workaround: store counters on a partition that is not prone to be running out of space.
