### ISSUE TITLE
"The receiver is overrun by more signals than expected"

### ISSUE THREAD

**Issue by climategadgets** [home-climate-control/dz#218]
### Expected Behavior
The system functions without interruptions.

### Actual Behavior
Intermittently, `InfluxDbLogger` stops writing data into InluxDB database. Exception trace follows.

### Contributing Factors

It is possible that the root cause is that [`windowTimeout()` can't handle backpressure](https://github.com/reactor/reactor-core/issues/1099).

### Acceptance Criteria
* Best case scenario: a solution is put in place that eliminates this problem altogether.
* Quick fix scenario: a solution is put in place that shifts backpressure handling elsewhere.

### Exception Trace

As of revision 7326d0962b6abe0288f2d1db3fee1666d48e695e (but likely originated at 33e54a8a1f0ecd5f5e44b33ac0649b0f5d504288 or before):

```
 reactor.core.Exceptions$OverflowException: The receiver is overrun by more signals than expected (bounded queue...)
        at reactor.core.Exceptions.failWithOverflow(Exceptions.java:220) ~[reactor-core-3.4.11.jar:3.4.11]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.FluxWindowTimeout] :
        reactor.core.publisher.Flux.windowTimeout
        net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:54)
Error has been observed at the following site(s):
        *__Flux.windowTimeout # at net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:54)
        |_     Flux.publishOn # at net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:55)
        |_       Flux.flatMap # at net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:56)
        |_           Flux.map # at net.sf.dz3r.view.influxdb.v3.ZoneSensorConverter.compute(ZoneSensorConverter.java:20)
        |_                    # at net.sf.dz3r.view.influxdb.v3.InfluxDbLogger.lambda$connect$1(InfluxDbLogger.java:123)
        *__________Flux.merge # at net.sf.dz3r.view.influxdb.v3.InfluxDbLogger.connect(InfluxDbLogger.java:121)
        *__________Flux.merge # at net.sf.dz3r.view.influxdb.v3.InfluxDbLogger.connect(InfluxDbLogger.java:132)
        |_     Flux.publishOn # at net.sf.dz3r.view.influxdb.v3.InfluxDbLogger.connect(InfluxDbLogger.java:140)
Stack trace:
                at reactor.core.Exceptions.failWithOverflow(Exceptions.java:220) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxWindowTimeout$WindowTimeoutSubscriber.onNext(FluxWindowTimeout.java:241) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:201) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmitScalar(FluxFlatMap.java:488) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:421) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxPublish$PublishSubscriber.drain(FluxPublish.java:477) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxPublish$PublishSubscriber.onNext(FluxPublish.java:268) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154) ~[reactor-core-3.4.11.jar:3.4.11]
                at net.sf.dz3r.device.driver.DriverNetworkMonitor.broadcastEvent(DriverNetworkMonitor.java:80) ~[dz3r-driver-3.6.8-SNAPSHOT.jar:?]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:196) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440) [reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527) [reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) [reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) [reactor-core-3.4.11.jar:3.4.11]
                at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
                at java.lang.Thread.run(Thread.java:829) [?:?]

```

**Comment by climategadgets** [comment]
More:
```
[ERROR] (boundedElastic-3) Operator called default onErrorDropped - reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.core.Exceptions$OverflowException: The receiver is overrun by more signals than expected (bounded queue...)
reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.core.Exceptions$OverflowException: The receiver is overrun by more signals than expected (bounded queue...)
Caused by: reactor.core.Exceptions$OverflowException: The receiver is overrun by more signals than expected (bounded queue...)
        at reactor.core.Exceptions.failWithOverflow(Exceptions.java:220)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Assembly trace from producer [reactor.core.publisher.FluxWindowTimeout] :
        reactor.core.publisher.Flux.windowTimeout
        net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:54)
Error has been observed at the following site(s):
        *__Flux.windowTimeout # at net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:54)
        |_     Flux.publishOn # at net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:55)
        |_       Flux.flatMap # at net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:56)
Stack trace:
                at reactor.core.Exceptions.failWithOverflow(Exceptions.java:220)
                at reactor.core.publisher.FluxWindowTimeout$WindowTimeoutSubscriber.onNext(FluxWindowTimeout.java:241)
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
                at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118)
                at reactor.core.publisher.FluxPublish$PublishSubscriber.drain(FluxPublish.java:477)
                at reactor.core.publisher.FluxPublish$PublishSubscriber.onNext(FluxPublish.java:268)
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793)
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718)
                at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154)
                at net.sf.dz3r.device.mqtt.v1.MqttListener.lambda$createFlux$3(MqttListener.java:168)
                at net.sf.dz3r.device.mqtt.v1.MqttListener.lambda$createFlux$5(MqttListener.java:193)
                at com.hivemq.client.internal.mqtt.mqtt3.Mqtt3AsyncClientView.lambda$callbackView$1(Mqtt3AsyncClientView.java:76)
                at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:303)
                at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:288)
                at com.hivemq.client.rx.FlowableWithSingle$SingleFutureSubscriber.onNext(FlowableWithSingle.java:406)
                at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber$Default.tryOnNextActual(FlowableWithSingleCombine.java:235)
                at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber.tryOnNext(FlowableWithSingleCombine.java:200)
                at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnConditionalSubscriber.runAsync(FlowableObserveOn.java:649)
                at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
                at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
                at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by climategadgets** [comment]
More:

```
 reactor.core.Exceptions$OverflowException: The receiver is overrun by more signals than expected (bounded queue...)
        at reactor.core.Exceptions.failWithOverflow(Exceptions.java:220) ~[reactor-core-3.4.11.jar:3.4.11]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.FluxWindowTimeout] :
        reactor.core.publisher.Flux.windowTimeout
        net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:54)
Error has been observed at the following site(s):
        *__Flux.windowTimeout ⇢ at net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:54)
        |_     Flux.publishOn ⇢ at net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:55)
        |_       Flux.flatMap ⇢ at net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:56)
        |_           Flux.map ⇢ at net.sf.dz3r.signal.filter.DoubleMedianSetFilter.compute(DoubleMedianSetFilter.java:30)
        *__________Flux.merge ⇢ at net.sf.dz3r.signal.filter.DoubleMedianSetFilter.compute(DoubleMedianSetFilter.java:34)
        |_           Flux.map ⇢ at net.sf.dz3r.signal.filter.AbstractMedianFilter.compute(AbstractMedianFilter.java:36)
        |_           Flux.map ⇢ at net.sf.dz3r.signal.filter.DoubleMedianSetFilter.compute(DoubleMedianSetFilter.java:36)
        |_           Flux.map ⇢ at net.sf.dz3r.view.influxdb.v3.SensorConverter.compute(SensorConverter.java:24)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.view.influxdb.v3.SensorConverter.compute(SensorConverter.java:25)
        |_                    ⇢ at net.sf.dz3r.view.influxdb.v3.InfluxDbLogger.lambda$connect$0(InfluxDbLogger.java:117)
        *__________Flux.merge ⇢ at net.sf.dz3r.view.influxdb.v3.InfluxDbLogger.connect(InfluxDbLogger.java:115)
        *__________Flux.merge ⇢ at net.sf.dz3r.view.influxdb.v3.InfluxDbLogger.connect(InfluxDbLogger.java:132)
        |_     Flux.publishOn ⇢ at net.sf.dz3r.view.influxdb.v3.InfluxDbLogger.connect(InfluxDbLogger.java:140)
Stack trace:
                at reactor.core.Exceptions.failWithOverflow(Exceptions.java:220) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxWindowTimeout$WindowTimeoutSubscriber.onNext(FluxWindowTimeout.java:241) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxPublish$PublishSubscriber.drain(FluxPublish.java:477) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxPublish$PublishSubscriber.onNext(FluxPublish.java:268) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154) ~[reactor-core-3.4.11.jar:3.4.11]
                at net.sf.dz3r.device.mqtt.v1.MqttListener.lambda$createFlux$3(MqttListener.java:168) ~[dz3r-mqtt-3.6.8-SNAPSHOT.jar:?]
                at net.sf.dz3r.device.mqtt.v1.MqttListener.lambda$createFlux$5(MqttListener.java:193) ~[dz3r-mqtt-3.6.8-SNAPSHOT.jar:?]
                at com.hivemq.client.internal.mqtt.mqtt3.Mqtt3AsyncClientView.lambda$callbackView$1(Mqtt3AsyncClientView.java:76) ~[hivemq-mqtt-client-1.2.2.jar:?]
                at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:303) ~[hivemq-mqtt-client-1.2.2.jar:?]
                at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:288) ~[hivemq-mqtt-client-1.2.2.jar:?]
                at com.hivemq.client.rx.FlowableWithSingle$SingleFutureSubscriber.onNext(FlowableWithSingle.java:406) ~[hivemq-mqtt-client-1.2.2.jar:?]
                at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber$Default.tryOnNextActual(FlowableWithSingleCombine.java:235) ~[hivemq-mqtt-client-1.2.2.jar:?]
                at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber.tryOnNext(FlowableWithSingleCombine.java:200) ~[hivemq-mqtt-client-1.2.2.jar:?]
                at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnConditionalSubscriber.runAsync(FlowableObserveOn.java:649) ~[rxjava-2.2.19.jar:?]
                at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176) ~[rxjava-2.2.19.jar:?]
                at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) ~[rxjava-2.2.19.jar:?]
                at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) ~[rxjava-2.2.19.jar:?]
                at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
                at java.lang.Thread.run(Thread.java:829) [?:?]
```
