### ISSUE TITLE
Pipeline overrun with slow actuators

### ISSUE THREAD

**Issue by climategadgets** [home-climate-control/dz#253]
### Expected Behavior
Things happen
### Actual Behavior
All pipelines to a single HVAC device actuator break with the exception trace below, rendering that device and all connected sensors inoperable. A problem manifested itself wit a Zigbee device, but it is likely that a Z-Wave device would behave in a similar way.
### Acceptance Criteria
No matter how slow an actuator is, the system must go on.
### Exception Trace
This trace is repeated for all the sensors and the HVAC device:
```
2022-11-20 02:34:07,201 ERROR UnitDirector boundedElastic-15 [] HVAC device error
 reactor.core.Exceptions$OverflowException: Could not emit tick 4288 due to lack of requests (interval doesn't support small downstream requests that replenish slower than the ticks)
        at reactor.core.Exceptions.failWithOverflow(Exceptions.java:233) ~[reactor-core-3.4.11.jar:3.4.11]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.FluxInterval] :
        reactor.core.publisher.Flux.interval
        net.sf.dz3r.signal.sensor.ShellSensor.getFlux(ShellSensor.java:80)
Error has been observed at the following site(s):
        *_______Flux.interval ⇢ at net.sf.dz3r.signal.sensor.ShellSensor.getFlux(ShellSensor.java:80)
        |_     Flux.publishOn ⇢ at net.sf.dz3r.signal.sensor.ShellSensor.getFlux(ShellSensor.java:81)
        |_           Flux.map ⇢ at net.sf.dz3r.signal.sensor.ShellSensor.getFlux(ShellSensor.java:82)
        |_       Flux.flatMap ⇢ at net.sf.dz3r.signal.sensor.ShellSensor.getFlux(ShellSensor.java:83)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:125)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:126)
        |_  Flux.doOnComplete ⇢ at net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:127)
        *__________Flux.merge ⇢ at net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:129)
        |_         Flux.share ⇢ at net.sf.dz3r.signal.sensor.ShellSensor.getFlux(ShellSensor.java:87) (observed 3 times)
        |_           Flux.map ⇢ at net.sf.dz3r.view.http.gae.v3.HttpConnectorGAE.getSensorFlux(HttpConnectorGAE.java:117)
        *__________Flux.merge ⇢ at net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:129)
        |_         Flux.share ⇢ at net.sf.dz3r.signal.sensor.ShellSensor.getFlux(ShellSensor.java:87) (observed 3 times)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.view.UnitObserver.lambda$init$2(UnitObserver.java:59)
        |_     Flux.publishOn ⇢ at net.sf.dz3r.view.UnitObserver.lambda$init$2(UnitObserver.java:60)
        *__________Flux.merge ⇢ at net.sf.dz3r.signal.filter.TimeoutGuard.compute(TimeoutGuard.java:129)
        |_         Flux.share ⇢ at net.sf.dz3r.signal.sensor.ShellSensor.getFlux(ShellSensor.java:87) (observed 3 times)
        |_           Flux.map ⇢ at net.sf.dz3r.model.UnitDirector.addZoneName(UnitDirector.java:181)
        |_           Flux.map ⇢ at net.sf.dz3r.model.Zone.compute(Zone.java:103)
        |_  Flux.doOnComplete ⇢ at net.sf.dz3r.controller.AbstractProcessController.compute(AbstractProcessController.java:107)
        *__________Flux.merge ⇢ at net.sf.dz3r.view.http.gae.v3.HttpConnectorGAE.getAggregateSensorFlux(HttpConnectorGAE.java:110)
        *__Flux.combineLatest ⇢ at net.sf.dz3r.controller.AbstractProcessController.compute(AbstractProcessController.java:102)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.model.Thermostat.compute(Thermostat.java:158)
        |_           Flux.map ⇢ at net.sf.dz3r.model.Thermostat.compute(Thermostat.java:164)
        |_  Flux.doOnComplete ⇢ at net.sf.dz3r.controller.AbstractProcessController.compute(AbstractProcessController.java:107)
        *__Flux.combineLatest ⇢ at net.sf.dz3r.controller.AbstractProcessController.compute(AbstractProcessController.java:102)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.model.Thermostat.compute(Thermostat.java:170)
        |_           Flux.map ⇢ at net.sf.dz3r.model.Thermostat.compute(Thermostat.java:171)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.model.Zone.compute(Zone.java:109)
        |_           Flux.map ⇢ at net.sf.dz3r.model.Zone.compute(Zone.java:112)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.model.Zone.compute(Zone.java:113)
        |_           Flux.map ⇢ at net.sf.dz3r.model.Zone.compute(Zone.java:117)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.model.Zone.compute(Zone.java:118)
        |_           Flux.map ⇢ at net.sf.dz3r.model.Zone.compute(Zone.java:121)
        |_                    ⇢ at net.sf.dz3r.model.UnitDirector.lambda$extractSensorFluxes$7(UnitDirector.java:174)
        *__________Flux.merge ⇢ at net.sf.dz3r.model.UnitDirector.connectFeeds(UnitDirector.java:123)
        |_       Flux.publish ⇢ at net.sf.dz3r.model.UnitDirector.connectFeeds(UnitDirector.java:124)
        |_         checkpoint ⇢ aggregate-sensor
        |_        Flux.filter ⇢ at net.sf.dz3r.model.ZoneController.compute(ZoneController.java:75)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.model.ZoneController.compute(ZoneController.java:76)
        |_           Flux.map ⇢ at net.sf.dz3r.model.ZoneController.compute(ZoneController.java:77)
        |_       Flux.publish ⇢ at net.sf.dz3r.model.UnitDirector.connectFeeds(UnitDirector.java:128)
        |_         checkpoint ⇢ zone-controller
        |_           Flux.map ⇢ at net.sf.dz3r.model.UnitDirector.connectFeeds(UnitDirector.java:130)
        |_        Flux.filter ⇢ at net.sf.dz3r.model.SingleStageUnitController.compute(SingleStageUnitController.java:35)
        |_           Flux.map ⇢ at net.sf.dz3r.model.SingleStageUnitController.compute(SingleStageUnitController.java:36)
        |_       Flux.publish ⇢ at net.sf.dz3r.model.UnitDirector.connectFeeds(UnitDirector.java:133)
        |_         checkpoint ⇢ unit-controller
        *_________Flux.concat ⇢ at net.sf.dz3r.model.UnitDirector.connectFeeds(UnitDirector.java:137)
        |_        Flux.filter ⇢ at net.sf.dz3r.device.actuator.SwitchableHvacDevice.compute(SwitchableHvacDevice.java:88)
        |_       Flux.flatMap ⇢ at net.sf.dz3r.device.actuator.SwitchableHvacDevice.compute(SwitchableHvacDevice.java:89)
        |_       Flux.publish ⇢ at net.sf.dz3r.model.UnitDirector.connectFeeds(UnitDirector.java:140) (observed 2 times)
        |_         checkpoint ⇢ hvac-device (observed 2 times)
        |_     Flux.publishOn ⇢ at net.sf.dz3r.model.UnitDirector.start(UnitDirector.java:199)
        *_________Flux.concat ⇢ at net.sf.dz3r.model.UnitDirector.connectFeeds(UnitDirector.java:137)
        |_        Flux.filter ⇢ at net.sf.dz3r.device.actuator.SwitchableHvacDevice.compute(SwitchableHvacDevice.java:88)
        |_       Flux.flatMap ⇢ at net.sf.dz3r.device.actuator.SwitchableHvacDevice.compute(SwitchableHvacDevice.java:89)
        |_       Flux.publish ⇢ at net.sf.dz3r.model.UnitDirector.connectFeeds(UnitDirector.java:140) (observed 2 times)
        |_         checkpoint ⇢ hvac-device (observed 2 times)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.view.http.gae.v3.HttpConnectorGAE.connect(HttpConnectorGAE.java:78)
        |_        Flux.filter ⇢ at net.sf.dz3r.view.http.gae.v3.HttpConnectorGAE.connect(HttpConnectorGAE.java:83)
        |_           Flux.map ⇢ at net.sf.dz3r.view.http.gae.v3.HttpConnectorGAE.connect(HttpConnectorGAE.java:84)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.view.http.gae.v3.ZoneRenderer.subscribeMode(ZoneRenderer.java:105)
Stack trace:
                at reactor.core.Exceptions.failWithOverflow(Exceptions.java:233) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:132) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59) ~[reactor-core-3.4.11.jar:3.4.11]
                at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73) ~[reactor-core-3.4.11.jar:3.4.11]
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
                at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
                at java.lang.Thread.run(Thread.java:829) [?:?]

```

**Comment by climategadgets** [comment]
This cannot be solved with a simple `onBackpressure*()` because it's the hardware devices that are slow to respond, and in a particular case of Zigbee and Z-Wave it may take minutes or hours for them to saturate while pretending they are acting normally - only to get stuck [semi] permanently while behaving erratically (apparently ignoring commands, or executing random commands from the buffer.

**Comment by climategadgets** [comment]
Freudian slip: commits for this issue had the #243 tag in them.
