### ISSUE TITLE
Economizer gets stuck on when NaN pops up in interim calculations

### ISSUE THREAD

**Issue by climategadgets** [home-climate-control/dz#329]
### Expected Behavior

Economizer continues working if sensor inputs are valid, and stops when they cease to be.

### Actual Behavior

`NaN` signal somewhere in the pipeline (tbd later) breaks the pipeline and causes the economizer to be stuck on (in this observed case). This is observed at rev. a8506bc0cb986de2f30ea0bc2195105c5f1a4b70 in `gh323-rsocket` branch but is likely present in `dev` as well.

### Related Issues

#328 with the difference that it was observed in cooling mode, and this bug has been observed in heating.

### Exception Traces

Late night, just capturing traces for further investigation.

1/2 

```
2024-11-11 14:30:15,264 ERROR AbstractEconomizer RxComputationThreadPool-1 [] Workshop-west: errored out
 java.lang.IllegalStateException: signal is NaN, components: setpoint=0.0,error=NaN,signal=NaN,p=NaN,i=0.5017015759999994,d=0.0
        at net.sf.dz3r.controller.pid.AbstractPidController.wrapCompute(AbstractPidController.java:139) ~[hcc-model-4.5.0-SNAPSHOT.jar:?]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.FluxCombineLatest] :
        reactor.core.publisher.Flux.combineLatest
        net.sf.dz3r.controller.AbstractProcessController.compute(AbstractProcessController.java:101)
Error has been observed at the following site(s):
        *__Flux.combineLatest ⇢ at net.sf.dz3r.controller.AbstractProcessController.compute(AbstractProcessController.java:101)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.device.actuator.economizer.v2.PidEconomizer.computeDeviceState(PidEconomizer.java:81)
        |_           Flux.map ⇢ at net.sf.dz3r.device.actuator.economizer.v2.PidEconomizer.computeDeviceState(PidEconomizer.java:84)
        |_  Flux.doOnComplete ⇢ at net.sf.dz3r.controller.AbstractProcessController.compute(AbstractProcessController.java:106)
        *__Flux.combineLatest ⇢ at net.sf.dz3r.controller.AbstractProcessController.compute(AbstractProcessController.java:101)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.device.actuator.economizer.v2.PidEconomizer.computeDeviceState(PidEconomizer.java:90)
        |_           Flux.map ⇢ at net.sf.dz3r.device.actuator.economizer.v2.PidEconomizer.computeDeviceState(PidEconomizer.java:91)
        |_           Flux.map ⇢ at net.sf.dz3r.device.actuator.economizer.AbstractEconomizer.initFluxes(AbstractEconomizer.java:180)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.device.actuator.economizer.AbstractEconomizer.initFluxes(AbstractEconomizer.java:185)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.device.actuator.economizer.AbstractEconomizer.initFluxes(AbstractEconomizer.java:186)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.device.actuator.economizer.AbstractEconomizer.initFluxes(AbstractEconomizer.java:187)
Original Stack Trace:
                at net.sf.dz3r.controller.pid.AbstractPidController.wrapCompute(AbstractPidController.java:139) ~[hcc-model-4.5.0-SNAPSHOT.jar:?]
                at net.sf.dz3r.controller.AbstractProcessController.compute(AbstractProcessController.java:135) ~[hcc-model-4.5.0-SNAPSHOT.jar:?]
                at reactor.core.publisher.Flux.lambda$combineLatest$2(Flux.java:219) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxCombineLatest$CombineLatestCoordinator.drainAsync(FluxCombineLatest.java:440) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxCombineLatest$CombineLatestCoordinator.drain(FluxCombineLatest.java:487) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxCombineLatest$CombineLatestCoordinator.innerValue(FluxCombineLatest.java:334) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxCombineLatest$CombineLatestInner.onNext(FluxCombineLatest.java:608) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:880) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:805) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:163) ~[reactor-core-3.6.9.jar:3.6.9]
                at net.sf.dz3r.device.actuator.economizer.AbstractEconomizer.recordIndoor(AbstractEconomizer.java:229) ~[hcc-model-4.5.0-SNAPSHOT.jar:?]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:196) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:547) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:988) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:547) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:988) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:716) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:592) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:975) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxReplay$SizeAndTimeBoundReplayBuffer.replayFused(FluxReplay.java:300) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxReplay$SizeAndTimeBoundReplayBuffer.replay(FluxReplay.java:494) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxReplay$ReplaySubscriber.onNext(FluxReplay.java:1345) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.SinkManyEmitterProcessor.drain(SinkManyEmitterProcessor.java:476) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.SinkManyEmitterProcessor.tryEmitNext(SinkManyEmitterProcessor.java:273) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100) ~[reactor-core-3.6.9.jar:3.6.9]
                at net.sf.dz3r.device.mqtt.v2async.MqttListenerImpl.callback(MqttListenerImpl.java:119) ~[hcc-mqtt-4.5.0-SNAPSHOT.jar:?]
                at net.sf.dz3r.device.mqtt.v2async.MqttListenerImpl.lambda$createFlux$4(MqttListenerImpl.java:89) ~[hcc-mqtt-4.5.0-SNAPSHOT.jar:?]
                at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:303) [hivemq-mqtt-client-1.3.3.jar:?]
                at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:288) [hivemq-mqtt-client-1.3.3.jar:?]
                at com.hivemq.client.rx.FlowableWithSingle$SingleFutureSubscriber.onNext(FlowableWithSingle.java:406) [hivemq-mqtt-client-1.3.3.jar:?]
                at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber$Default.tryOnNextActual(FlowableWithSingleCombine.java:235) [hivemq-mqtt-client-1.3.3.jar:?]
                at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber.tryOnNext(FlowableWithSingleCombine.java:200) [hivemq-mqtt-client-1.3.3.jar:?]
                at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnConditionalSubscriber.runAsync(FlowableObserveOn.java:649) [rxjava-2.2.21.jar:?]
                at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176) [rxjava-2.2.21.jar:?]
                at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) [rxjava-2.2.21.jar:?]
                at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) [rxjava-2.2.21.jar:?]
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
                at java.base/java.lang.Thread.run(Thread.java:840) [?:?]

```
2/2

```
2024-11-11 14:30:15,266 ERROR Loggers$Slf4JLogger RxComputationThreadPool-1 [] Operator called default onErrorDropped
 reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IllegalStateException: signal is NaN, components: setpoint=0.0,error=NaN,signal=NaN,p=NaN,i=0.5017015759999994,d=0.0
Caused by: java.lang.IllegalStateException: signal is NaN, components: setpoint=0.0,error=NaN,signal=NaN,p=NaN,i=0.5017015759999994,d=0.0
        at net.sf.dz3r.controller.pid.AbstractPidController.wrapCompute(AbstractPidController.java:139) ~[hcc-model-4.5.0-SNAPSHOT.jar:?]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.FluxCombineLatest] :
        reactor.core.publisher.Flux.combineLatest
        net.sf.dz3r.controller.AbstractProcessController.compute(AbstractProcessController.java:101)
Error has been observed at the following site(s):
        *__Flux.combineLatest ⇢ at net.sf.dz3r.controller.AbstractProcessController.compute(AbstractProcessController.java:101)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.device.actuator.economizer.v2.PidEconomizer.computeDeviceState(PidEconomizer.java:81)
        |_           Flux.map ⇢ at net.sf.dz3r.device.actuator.economizer.v2.PidEconomizer.computeDeviceState(PidEconomizer.java:84)
        |_  Flux.doOnComplete ⇢ at net.sf.dz3r.controller.AbstractProcessController.compute(AbstractProcessController.java:106)
        *__Flux.combineLatest ⇢ at net.sf.dz3r.controller.AbstractProcessController.compute(AbstractProcessController.java:101)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.device.actuator.economizer.v2.PidEconomizer.computeDeviceState(PidEconomizer.java:90)
        |_           Flux.map ⇢ at net.sf.dz3r.device.actuator.economizer.v2.PidEconomizer.computeDeviceState(PidEconomizer.java:91)
        |_           Flux.map ⇢ at net.sf.dz3r.device.actuator.economizer.AbstractEconomizer.initFluxes(AbstractEconomizer.java:180)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.device.actuator.economizer.AbstractEconomizer.initFluxes(AbstractEconomizer.java:185)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.device.actuator.economizer.AbstractEconomizer.initFluxes(AbstractEconomizer.java:186)
        |_      Flux.doOnNext ⇢ at net.sf.dz3r.device.actuator.economizer.AbstractEconomizer.initFluxes(AbstractEconomizer.java:187)
        |_     Flux.doOnError ⇢ at net.sf.dz3r.device.actuator.economizer.AbstractEconomizer.initFluxes(AbstractEconomizer.java:189)
        |_  Flux.doOnComplete ⇢ at net.sf.dz3r.device.actuator.economizer.AbstractEconomizer.initFluxes(AbstractEconomizer.java:190)
Original Stack Trace:
                at net.sf.dz3r.controller.pid.AbstractPidController.wrapCompute(AbstractPidController.java:139) ~[hcc-model-4.5.0-SNAPSHOT.jar:?]
                at net.sf.dz3r.controller.AbstractProcessController.compute(AbstractProcessController.java:135) ~[hcc-model-4.5.0-SNAPSHOT.jar:?]
                at reactor.core.publisher.Flux.lambda$combineLatest$2(Flux.java:219) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxCombineLatest$CombineLatestCoordinator.drainAsync(FluxCombineLatest.java:440) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxCombineLatest$CombineLatestCoordinator.drain(FluxCombineLatest.java:487) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxCombineLatest$CombineLatestCoordinator.innerValue(FluxCombineLatest.java:334) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxCombineLatest$CombineLatestInner.onNext(FluxCombineLatest.java:608) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:880) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:805) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:163) ~[reactor-core-3.6.9.jar:3.6.9]
                at net.sf.dz3r.device.actuator.economizer.AbstractEconomizer.recordIndoor(AbstractEconomizer.java:229) ~[hcc-model-4.5.0-SNAPSHOT.jar:?]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:196) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:547) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:988) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:547) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:988) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:716) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:592) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:975) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxReplay$SizeAndTimeBoundReplayBuffer.replayFused(FluxReplay.java:300) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxReplay$SizeAndTimeBoundReplayBuffer.replay(FluxReplay.java:494) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.FluxReplay$ReplaySubscriber.onNext(FluxReplay.java:1345) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.SinkManyEmitterProcessor.drain(SinkManyEmitterProcessor.java:476) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.SinkManyEmitterProcessor.tryEmitNext(SinkManyEmitterProcessor.java:273) ~[reactor-core-3.6.9.jar:3.6.9]
                at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100) ~[reactor-core-3.6.9.jar:3.6.9]
                at net.sf.dz3r.device.mqtt.v2async.MqttListenerImpl.callback(MqttListenerImpl.java:119) ~[hcc-mqtt-4.5.0-SNAPSHOT.jar:?]
                at net.sf.dz3r.device.mqtt.v2async.MqttListenerImpl.lambda$createFlux$4(MqttListenerImpl.java:89) ~[hcc-mqtt-4.5.0-SNAPSHOT.jar:?]
                at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:303) [hivemq-mqtt-client-1.3.3.jar:?]
                at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:288) [hivemq-mqtt-client-1.3.3.jar:?]
                at com.hivemq.client.rx.FlowableWithSingle$SingleFutureSubscriber.onNext(FlowableWithSingle.java:406) [hivemq-mqtt-client-1.3.3.jar:?]
                at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber$Default.tryOnNextActual(FlowableWithSingleCombine.java:235) [hivemq-mqtt-client-1.3.3.jar:?]
                at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber.tryOnNext(FlowableWithSingleCombine.java:200) [hivemq-mqtt-client-1.3.3.jar:?]
                at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnConditionalSubscriber.runAsync(FlowableObserveOn.java:649) [rxjava-2.2.21.jar:?]
                at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176) [rxjava-2.2.21.jar:?]
                at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) [rxjava-2.2.21.jar:?]
                at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) [rxjava-2.2.21.jar:?]
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
                at java.base/java.lang.Thread.run(Thread.java:840) [?:?]

```

**Comment by climategadgets** [comment]
Root cause: `changeoverDelta` being zero, and `indoorTemperature` being exactly equal to `ambientTemperature` resulted in `(Infinity * 0)` expression which produced `NaN` - which in turn broke the pipeline.

Fixed as of rev. a1bf422a829d1ded35b9b90c55f55729f919b434 (`dev` branch).
