### ISSUE TITLE
File based usage counter blows up if the persistent storage doesn't exist

### ISSUE THREAD

**Issue by climategadgets** [home-climate-control/dz#7]
Workaround: touch ${persistent-storage-file}

Trace:

    java.io.FileNotFoundException: ${persistent-storage-file-removed-for-privacy} (No such file or directory)
            at java.io.FileOutputStream.open(Native Method)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:212)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:99)
            at java.io.FileWriter.<init>(FileWriter.java:63)
            at net.sf.dz3.util.counter.FileUsageCounter.save(FileUsageCounter.java:158)

**Comment by climategadgets** [comment]
Correction: this only happens if the file path includes non-existing directories.
