### ISSUE TITLE
Failure to publish an MQTT message at startup

### ISSUE THREAD

**Issue by climategadgets** [home-climate-control/dz#98]
Revision reported against: ac66247bb20923674d37a591d2e780642f877ca3

This exception has been observed once upon startup and doesn't affect further operation. Still, it would've been nice if this message was simply queued.

```
2019-05-31 21:38:57,875 ERROR ImmediateExchanger Thread-2 [run] Unexpected exception
java.lang.NullPointerException: null
        at net.sf.dz3.view.mqtt.v1.MqttConnector$UpstreamBlockExchanger.send(MqttConnector.java:404) ~[dz3-mqtt-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.view.mqtt.v1.MqttConnector$UpstreamBlockExchanger.send(MqttConnector.java:379) ~[dz3-mqtt-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.view.mqtt.v1.ImmediateExchanger.exchange(ImmediateExchanger.java:60) ~[dz3-mqtt-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.view.mqtt.v1.ImmediateExchanger.run(ImmediateExchanger.java:26) [dz3-mqtt-3.6.8-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
2019-05-31 21:38:57,961 ERROR MqttConnector$UpstreamBlockExchanger Thread-2 [run, exchange, send] can't publish, ignored, is this a persistent error?
org.eclipse.paho.client.mqttv3.MqttException: Client is not connected
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:199) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1355) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
        at org.eclipse.paho.client.mqttv3.MqttClient.publish(MqttClient.java:583) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
        at net.sf.dz3.view.mqtt.v1.MqttConnector$UpstreamBlockExchanger.send(MqttConnector.java:404) [dz3-mqtt-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.view.mqtt.v1.MqttConnector$UpstreamBlockExchanger.send(MqttConnector.java:379) [dz3-mqtt-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.view.mqtt.v1.ImmediateExchanger.exchange(ImmediateExchanger.java:60) [dz3-mqtt-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.view.mqtt.v1.ImmediateExchanger.run(ImmediateExchanger.java:26) [dz3-mqtt-3.6.8-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
```

**Comment by climategadgets** [comment]
No longer observed
